export const DEFAULT_CONFIG = {
  MAX_DEADHEAD_KM: 150, MIN_RELIABILITY: 0.75, MIN_PERFORMANCE_SAMPLES: 5,
  RATE_LOOKBACK_DAYS: 30, RATE_FALLBACK_LOOKBACK_DAYS: 90,
  MIN_ACCEPTED_RATE_SAMPLES: 5, MIN_RATE_BAND_SAMPLES: 10, MIN_GLOBAL_RATE_SAMPLES: 20,
  COMMERCIAL_FLOOR: 0.10, DEMAND_SPIKE_THRESHOLD: 0.25,
  CONCENTRATION_WARNING: 0.35, CONCENTRATION_HIGH: 0.45,
  RATE_RECOMMENDATION_MAX_INCREASE: 0.20, RATE_SEARCH_INCREMENT: 0.01,
  MIN_MATERIAL_COVERAGE_IMPROVEMENT: 0.10,
  HEALTHY_COVERAGE: 1.20, WATCH_COVERAGE: 1.00, AT_RISK_COVERAGE: 0.75,
  CRITICAL_RISK: 75, HIGH_RISK: 60, MEDIUM_RISK: 40,
}
export type Config = typeof DEFAULT_CONFIG
